# numpy入门

## 数组基础

In [1]:
# 创建一个数组
# 1D Array
a = np.array([0, 1, 2, 3, 4])
b = np.array((0, 1, 2, 3, 4))
c = np.arange(5)
d = np.linspace(0, 2*np.pi, 5)

print(a) # >>>[0 1 2 3 4]
print(b) # >>>[0 1 2 3 4]
print(c) # >>>[0 1 2 3 4]
print(d) # >>>[ 0.          1.57079633  3.14159265  4.71238898  6.28318531]
print(a[3]) # >>>3

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0.         1.57079633 3.14159265 4.71238898 6.28318531]
3


In [2]:
# MD Array,
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])

print(a[2,4]) # >>>25

25


## ndarray 对象

## numpy题

In [1]:
# 使用别名“np“调用numpy

import numpy as np

In [2]:
# 显示当前numpy库的版本号和配置信息。(★☆☆)(np.__version__, np.show_config)

print(np.__version__)
print(np.show_config())
#v._n.()是常见的函数命名方式

1.23.5
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/python/mambaforge/envs/opencv/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/python/mambaforge/envs/opencv/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/python/mambaforge/envs/opencv/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/python/mambaforge/envs/opencv/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,

In [3]:
# 创建一个大小为10的零向量。(★☆☆)(np.zeros)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 如何获取任意一个数组占用的内存大小？(★☆☆)(size, itemsize)

a = np.random.rand(2,3)
print('%d bytes' %(a.size * a.itemsize))

48 bytes


In [5]:
# 如何在命令行中获取numpy的add函数的文档？(★☆☆)(http://np.info)

np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
# 创建一个大小为10的零向量，使之第5个元素为1。(★☆☆)(array[4])

a = np.zeros(10)
a[4] = 1

print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
# (7) 创建一个向量，使它的值为10到49。(★☆☆)(np.arange)

a = np.arange(10,50)

print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
# (9) 创建一个 3x3 矩阵，其值为0到8。(★☆☆)(reshape)

np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# (10) 列出 [1,2,0,0,4,0] 该数组中非零元素的索引。(★☆☆)(np.nonzero)

np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

In [10]:
# (11) 创建一个 3x3 的单位矩阵。(★☆☆)(np.eye)

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# (12) 利用随机数创建一个 3x3x3 的数组。 (★☆☆)(np.random.random)

np.random.random((3,3,3))
#上式为参考答案，但个人觉得以下的写法更简单：
np.random.rand(3,3,3)

array([[[0.70300176, 0.13673023, 0.79705197],
        [0.64913941, 0.38340662, 0.15086397],
        [0.61481378, 0.96751885, 0.26676689]],

       [[0.75644127, 0.53782582, 0.0896166 ],
        [0.76910409, 0.27924564, 0.01273855],
        [0.72832536, 0.79265653, 0.8225213 ]],

       [[0.11064142, 0.94803841, 0.03707379],
        [0.03636034, 0.66996   , 0.96003914],
        [0.58632985, 0.82255807, 0.18397357]]])

In [12]:
# (13) 利用随机数创建一个 10x10 的数组，并获取数组的最小元素和最大元素。(★☆☆)(min, max)

a = np.random.rand(10,10)
print(np.min(a),np.max(a))

0.01981002217646244 0.9870149571245954


In [13]:
# (14) 创建一个大小为30的随机向量，并求取均值。(★☆☆)(mean)

np_mean = np.random.rand(30).mean()
print("np_mean", np_mean)

np_mean 0.5079905140803417


In [14]:
# (15) 创建一个二维数组，使其边界全部为1，内部全部为0。(★☆☆)(array[1:-1, 1:-1])

#参考答案
a = np.ones((10,10))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
#(16) 如何给一个已有的数组加上一个边界（值为0）？(★☆☆)(np.pad)

a = np.random.randint(1,20,(5,5)) #生成一个5x5的随机整数数组
b = np.pad(a,pad_width=1,mode='constant',constant_values=0) #为数组加上边界
a, b

(array([[ 9, 16, 18,  8,  3],
        [ 5,  6,  5, 10, 12],
        [ 7, 12,  4, 18, 17],
        [ 1,  4,  8,  5, 12],
        [ 6,  9,  4,  1, 15]]),
 array([[ 0,  0,  0,  0,  0,  0,  0],
        [ 0,  9, 16, 18,  8,  3,  0],
        [ 0,  5,  6,  5, 10, 12,  0],
        [ 0,  7, 12,  4, 18, 17,  0],
        [ 0,  1,  4,  8,  5, 12,  0],
        [ 0,  6,  9,  4,  1, 15,  0],
        [ 0,  0,  0,  0,  0,  0,  0]]))

In [16]:
# (17) 以下的表达式的运行结果为？(★☆☆)(NaN = not a number, Inf = infinity)

print(0 * np.nan) #输出：nan
print(np.nan == np.nan) #输出：False
print(np.inf > np.nan) #输出：False
print(np.nan - np.nan) #输出：nan
print(np.nan in set([np.nan])) #输出：True
print(0.3 == 3 * 0.1) #输出：False

nan
False
False
nan
True
False


In [17]:
# (18) 创建一个 5x5 矩阵，使得数字 1,2,3,4 恰好处在对角线下方。(★☆☆)(np.diag)

#参考答案
np.diag(1+np.arange(4),k=-1)

#另一种方法
np.diag(np.arange(1,5),-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [18]:
# (19) 创建一个8x8数组，使之形成棋盘格图案。 (★☆☆)(array[::2])

#参考答案
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

#另一种方法
a = np.zeros((8,8), dtype=int)
a[::2,::2]=1
a[1::2,1::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [19]:
# (20) 对于一个形为 (6,7,8) 的数组，如何用形似 (x,y,z) 的索引取出其第100个元素？(★☆☆)(np.unravel_index)

np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [20]:
# (21) 使用 tile 函数创建一个 8x8 棋盘格矩阵。(★☆☆)(np.tile)

np.tile( np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [21]:
# (22) 对一个 5x5 矩阵进行标准化。(★☆☆)((x - mean) / std)

a = np.random.random((5,5))
a = (a - np.mean (a)) / (np.std (a))
print(a)

[[-1.06581696 -1.23124111 -0.60471075 -0.46693943 -0.00248605]
 [ 1.22339078 -1.07897823 -0.84095079  1.68669429  0.74460455]
 [-0.24883185  0.16771653 -1.1096163   1.32362468  1.37642553]
 [-0.07149852 -1.04816451 -0.87676753  1.66750064 -0.98993297]
 [-0.30446015 -0.80482914 -0.13875247  1.40830318  1.28571658]]


In [25]:
#(23) 创建一个自定义类型，用四个无符号字节存放颜色信息(RGBA)。 (★☆☆)(np.dtype)
color = np.dtype([("r", np.ubyte, (1,)),
                  ("g", np.ubyte, (1,)),
                  ("b", np.ubyte, (1,)),
                  ("a", np.ubyte, (1,))])
print(color)

[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]


In [23]:
# (24) 矩阵乘法（点乘）：5x3矩阵 乘 3x2矩阵。(★☆☆)(np.dot | @)

#参考答案1
np.dot(np.ones((5,3)), np.ones((3,2)))

#参考答案2，python3.5及以上支持
np.ones((5,3)) @ np.ones((3,2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])